### ISSUE TITLE
compatibility with ASP MVC core 1.1

### ISSUE THREAD

**Issue by weedkiller** [mfidemraizer/stackredis.aspnet.identity#4]
Hi I am trying to use the identity in the latest version I get exceptions on running the service stack sample

**Comment by mfidemraizer** [comment]
@weedkiller 

First of all, thank you for your interest on this project.

Honestly, I won't doubt your statement, because when I implemented this custom store based on StackExchange.Redis, .NET Core didn't exist at all.

It would be great that you provide the following info:

1. The exception and its stack trace.
2. Do you have a sample project to let me dig into the issue? You can post a new comment attaching a ZIP file with a sample code.

Thank you!
